<?xml version="1.0"?>

<robot xmlns:xacro="macros_xacro">

    <xacro:arg name="details" default="quality"/>
    <xacro:arg name="car_model" default="lincoln"/>


    <xacro:property name="chassis_height" value="1.3"/>
    <xacro:property name="chassis_length" value="5"/>
    <xacro:property name="chassis_width" value="2.2"/>
    <xacro:property name="chassis_mass" value="2050"/>
    <xacro:property name="chassis_mass_ixx" value="647"/>
    <xacro:property name="chassis_mass_iyy" value="3291"/>
    <xacro:property name="chassis_mass_izz" value="3360"/>
    <xacro:property name="chassis_mass_ixz" value="-31"/>

    <xacro:property name="tyre_radius" value="0.356"/>
    <xacro:property name="tyre_mass" value="40"/>
    <xacro:property name="tyre_width" value="0.229"/>
    <xacro:property name="tyre_mass_ixx" value="2.0"/>
    <xacro:property name="tyre_mass_iyy" value="2.0"/>
    <xacro:property name="tyre_mass_izz" value="2.0"/>

    <xacro:property name="steering_column_weight" value="2.0"/>
    <xacro:property name="steering_column_radius" value="0.05"/>
    <xacro:property name="steering_column_length" value="0.5"/>
    <xacro:property name="distanceX_CM_to_rear_wheel_axis" value="-1.15"/>
    <xacro:property name="distanceX_CM_to_front_wheel_axis" value="1.65"/>
    <xacro:property name="distanceY_CM_to_wheel_center" value="0.8"/>
    <xacro:property name="distanceZ_CM_to_wheel_center" value="-0.5"/>
    <xacro:property name="wheelbase" value="${distanceX_CM_to_front_wheel_axis-distanceX_CM_to_rear_wheel_axis}"/>
    <xacro:property name="axle_track" value="${2*distanceY_CM_to_wheel_axis}"/>

    <!-- Sensors location setup params -->
    <xacro:property name="lidar_height" value="1.0"/>
    <xacro:property name="camera_height" value="0.625"/>

</robot>