TebLocalPlannerROS:

 map_topic: map
 odom_topic: odom
    
 # Trajectory
 teb_autosize: True
 dt_ref: 0.2
 dt_hysteresis: 0.02
 global_plan_overwrite_orientation: True
 allow_init_with_backwards_motion: True
 max_global_plan_lookahead_dist: 10.0
 global_plan_viapoint_sep: 2.0
 feasibility_check_no_poses: -1
 feasibility_check_lookahead_distance: 10.0
 exact_arc_length: False
 publish_feedback: False
 prevent_look_ahead_poses_near_goal: 2.0

 # ViaPoints
 global_plan_viapoint_sep: 2.0
 via_points_ordered: False

 # Robot
 max_vel_x: 5.6
 max_vel_x_backwards: 1.0
 max_vel_y: 0.0
 max_vel_theta: 0.2
 acc_lim_x: 6.0
 acc_lim_theta: 0.1
 is_footprint_dynamic: True
 use_proportional_saturation: False
 transform_tolerance: 10.0

 ## Robot/Carlike ##
 min_turning_radius: 7.0
 wheelbase: 2.8
 cmd_angle_instead_rotvel: True
 footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
   type: "polygon"
   vertices: [ [3.25, 1.5], [3.25, -1.5], [-2.5, -1.5], [-2.5, 1.5] ] # for type "polygon"

 # GoalTolerance
    
 xy_goal_tolerance: 0.5
 yaw_goal_tolerance: 0.4
 free_goal_vel: False
 complete_global_plan: True
    
 # Obstacles
    
 min_obstacle_dist: 0.1
 inflation_dist: 0.5
 dynamic_obstacle_inflation_dist: 0.75
 include_dynamic_obstacles: True
 include_costmap_obstacles: True
 costmap_obstacles_behind_robot_dist: 5.0
 obstacle_poses_affected: 15

 ## Obstacle/VelocityRatio
 obstacle_proximity_ratio_max_vel: 0.5
 obstacle_proximity_lower_bound: 0.5
 obstacle_proximity_higher_bound: 2.5

 # Optimization
    
 no_inner_iterations: 5
 no_outer_iterations: 4
 optimization_activate: True
 optimization_verbose: False
 penalty_epsilon: 0.0
 weight_max_vel_x: 100
 weight_max_vel_theta: 0.1
 weight_acc_lim_x: 10
 weight_acc_lim_theta: 0.1
 weight_kinematics_nh: 1000
 weight_kinematics_forward_drive: 1000
 weight_kinematics_turning_radius: 10
 weight_optimaltime: 100 # must be > 0
 weight_shortest_path: 10
 weight_obstacle: 1000
 weight_inflation: 10.0
 weight_dynamic_obstacle: 10
 weight_dynamic_obstacle_inflation: 0.2
 weight_viapoint: 1
 weight_adapt_factor: 2
 obstacle_cost_exponent: 1

 # Homotopy Class Planner

 enable_homotopy_class_planning: True
 enable_multithreading: True
 max_number_classes: 4
 selection_cost_hysteresis: 1.0
 selection_prefer_initial_plan: 10.0
 selection_obst_cost_scale: 10.0
 selection_alternative_time_cost: False

 roadmap_graph_no_samples: 10
 roadmap_graph_area_width: 5
 roadmap_graph_area_length_scale: 1.0
 h_signature_prescaler: 0.5
 h_signature_threshold: 0.1
 obstacle_heading_threshold: 0.45
 viapoints_all_candidates: True
 delete_detours_backwards: True
 max_ratio_detours_duration_best_duration: 5.0
 visualize_hc_graph: False
 visualize_with_time_as_z_axis_scale: False

# Recovery
 
 shrink_horizon_backup: True
 shrink_horizon_min_duration: 10
 oscillation_recovery: True
 oscillation_v_eps: 0.1
 oscillation_omega_eps: 0.1
 oscillation_recovery_min_duration: 10
 oscillation_filter_duration: 10