TrajectoryPlannerROS:
    min_vel_x: -50.0
    max_vel_x: 50.0
    min_vel_theta: -0.7
    max_vel_theta: 0.7
    min_in_place_vel_theta: 0.4
    escape_vel: -10.0
  
    acc_lim_theta: 1.0
    acc_lim_x: 10.0
    
    holonomic_robot: false

    xy_goal_tolerance: 0.1
    yaw_goal_tolerance: 0.2

    meter_scoring: true
    path_distance_bias: 50.0
    goal_distance_bias: 40.0
    occdist_scale:  1.0

    sim_time: 2.0
