global_costmap:
   plugins:
      - {name: 2d_slam_map_layer, type: "costmap_2d::VoxelLayer"}
      - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
   2d_slam_map_layer:
      observation_sources: 3d_map
      3d_map:
         sensor_frame: ""
         data_type: PointCloud2
         topic: /hdl_graph_slam/map_points
         marking: true
         clearing: true
         min_obstacle_height: 1.0
         max_obstacle_height: 5.0
         obstacle_range: 250.0
         raytrace_range: 250.0
   inflation_layer:
      inflation_radius: 5.0
      cost_scaling_factor: 0.5

   global_frame: map
   robot_base_frame: base_link
   update_frequency: 0.2
   publish_frequency: 0.2
   rolling_window: true
   width: 250.0
   height: 250.0
   resolution: 1.0
   transform_tolerance: 10.0