<?xml version="1.0"?>

<robot name="test_robot"
  xmlns:xacro="test">

  <xacro:include filename="$(find go_car_description)/urdf/include/params.xacro"/>
  <xacro:include filename="$(find go_car_description)/urdf/include/snippets.xacro"/>
  <xacro:include filename="$(find go_car_description)/urdf/include/links.xacro"/>
  <xacro:include filename="$(find go_car_description)/urdf/include/sensors.xacro"/>

  <!-- First tf level -->
  <link name="base_link"/>
  <joint name="base_to_chassis" type="fixed">
    <parent link="base_link"/>
    <child link="chassis_link"/>
    <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
  </joint>
  <joint name="chassis_to_left_steering_column" type="revolute">
    <parent link="chassis_link"/>
    <child link="left_steering_column_link"/>
    <axis xyz="0.0 0.0 1"/>
    <origin xyz="${distanceX_CM_to_front_wheel_axis} ${distanceY_CM_to_wheel_center} ${distanceZ_CM_to_wheel_center}" rpy="0.0 0.0 0.0"/>
    <limit lower="${-6/9*pi/2}" upper="${6/9*pi/2}" effort="100000" velocity="100000"/>
  </joint>
  <joint name="chassis_to_right_steering_column" type="revolute">
    <parent link="chassis_link"/>
    <child link="right_steering_column_link"/>
    <axis xyz="0.0 0.0 1"/>
    <origin xyz="${distanceX_CM_to_front_wheel_axis} ${-distanceY_CM_to_wheel_center} ${distanceZ_CM_to_wheel_center}" rpy="0.0 0.0 0.0"/>
    <limit lower="${-6/9*pi/2}" upper="${6/9*pi/2}" effort="100000" velocity="100000"/>
  </joint>

  <!-- Second tf level -->
  <xacro:chassis_link details="$(arg details)"/>
  <joint name="chassis_to_rear_left_wheel" type="continuous">
    <parent link="chassis_link"/>
    <child link="rear_left_wheel_link"/>
    <origin xyz="${distanceX_CM_to_rear_wheel_axis} ${distanceY_CM_to_wheel_center} ${distanceZ_CM_to_wheel_center}" rpy="0.0 0.0 0.0"/>
    <axis xyz="0.0 1.0 0.0"/>
    <limit effort="100000" velocity="100000"/>
  </joint>
  <joint name="chassis_to_rear_right_wheel" type="continuous">
    <parent link="chassis_link"/>
    <child link="rear_right_wheel_link"/>
    <origin xyz="${distanceX_CM_to_rear_wheel_axis} ${-distanceY_CM_to_wheel_center} ${distanceZ_CM_to_wheel_center}" rpy="0.0 0.0 0.0"/>
    <axis xyz="0.0 1.0 0.0"/>
    <limit effort="100000" velocity="100000"/>
  </joint>

  <xacro:steering_column_link RL="left"/>
  <xacro:steering_column_link RL="right"/>
  <joint name="steering_column_to_front_left_wheel" type="continuous">
    <parent link="left_steering_column_link"/>
    <child link="front_left_wheel_link"/>
    <axis xyz="0.0 1.0 0.0"/>
    <limit effort="100000" velocity="100000"/>
  </joint>
  <joint name="steering_column_to_front_right_wheel" type="continuous">
    <parent link="right_steering_column_link"/>
    <child link="front_right_wheel_link"/>
    <axis xyz="0.0 1.0 0.0"/>
    <limit effort="100000" velocity="100000"/>
  </joint>

  <!-- Third tf level -->
  <xacro:wheel_link FR="rear" RL="left"/>
  <xacro:wheel_link FR="rear" RL="right"/>
  <xacro:wheel_link FR="front" RL="left"/>
  <xacro:wheel_link FR="front" RL="right"/>
  <joint name="chassis_to_camera" type="fixed">
    <parent link="chassis_link"/>
    <child link="camera_link"/>
    <origin xyz="0.0 0.0 0.8" rpy="0.0 0.0 0.0"/>
  </joint>
  <joint name="chassis_to_lidar" type="fixed">
    <parent link="chassis_link"/>
    <child link="lidar_link"/>
    <origin xyz="${chassis_length/2+0.25} 0.0 -0.25" rpy="0.0 0.0 0.0"/>
  </joint>

  <!-- Gazebo -->
  <xacro:include filename="$(find go_car_description)/urdf/include/gazebo.xacro"/>

</robot>