go_car:
  control:
    steering:
      joints_names: {right: chassis_to_right_steering_column, left: chassis_to_left_steering_column}
      gains: {p: 15000.0, i: 10000.0, d: 1000.0, i_max: 500.0, i_min: -500.0, output_max: 1500.0 , output_min: -1500.0}
    speed:
      joints_names: {right: chassis_to_rear_right_wheel, left: chassis_to_rear_left_wheel}
      gains: {p: 500.0, i: 0.0, d: 0.0, i_max: 100.0, i_min: -100.0, output_max: 1500.0 , output_min: -1500.0}

