go_car:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  joint1_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: back_left_wheel_joint
    pid: {p: 2000.0, i: 0.5, d: 10.0, i_clamp_min: -100.0, i_clamp_max: 100.0}
  joint2_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: back_right_wheel_joint
    pid: {p: 200.0, i: 0.5, d: 10.0, i_clamp_min: -100.0, i_clamp_max: 100.0}
  front_left_steering_position_controller:
    type: effort_controllers/JointPositionController
    joint: front_left_steering_joint
    pid: {p: 2000.0, i: 0.1, d: 0.0, i_clamp_min: -100.0, i_clamp_max: 10.0}
  front_right_steering_position_controller:
    type: effort_controllers/JointPositionController
    joint: front_right_steering_joint
    pid: {p: 2000.0, i: 0.1, d: 0.0, i_clamp_min: -100.0, i_clamp_max: 10.0}