go_car:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  velocity_controller_right:
    type: effort_controllers/JointVelocityController
    joint: chassis_to_rear_right_wheel
    pid: {p: 2000.0, i: 0.5, d: 10.0, i_clamp_min: -100.0, i_clamp_max: 100.0}
  velocity_controller_left:
    type: effort_controllers/JointVelocityController
    joint: chassis_to_rear_left_wheel
    pid: {p: 2000.0, i: 0.5, d: 10.0, i_clamp_min: -100.0, i_clamp_max: 100.0}
  steering_controller:
    type: effort_controllers/JointGroupPositionController
    joints:
      - base_to_left_steering_column
      - base_to_right_steering_column
    base_to_left_steering_column:
      pid: {p: 1000000.0, i: 0.0, d: 0.0, i_clamp_min: -100.0, i_clamp_max: 100.0}
    base_to_right_steering_column:
      pid: {p: 1000000.0, i: 0.0, d: 0.0, i_clamp_min: -100.0, i_clamp_max: 100.0}
