go_car:
  control:
    steering:
      joints_names: {right: base_to_right_steering_column, left: base_to_left_steering_column}
      gains: {p: 100000.0, i: 0.0, d: 0.0, i_max: 10.0, i_min: -10.0, output_max: 2000.0 , output_min: -2000.0}
    speed:
      joints_names: {right: chassis_to_rear_right_wheel, left: chassis_to_rear_left_wheel}
      gains: {p: 5000.0, i: 0.0, d: 0.0, i_max: 100.0, i_min: -100.0, output_max: 2000.0 , output_min: -2000.0}

